### ISSUE TITLE
Unescaping escaped text within html

### ISSUE THREAD

**Issue by varunjain99** [rushter/selectolax#34] opened 2021-03-17 22:44 UTC
When the text inside a tag is escaped, it seems that it gets unescaped with the text() call. For example:

```
sample_parser = HTMLParser("""<a href="https://stackoverflow.com/questions/20771400">&lt;script&gt; tag vs &lt;script type = \'text/javascript\'&gt; tag</a>""")
print(sample_parser.body.text())
```

prints out
 ```<script> tag vs <script type = 'text/javascript'> tag```

I think it would make more sense to print out
```&lt;script&gt; tag vs &lt;script type = \'text/javascript\'&gt; tag```

**Comment by rushter** [comment] 2021-03-18 06:37
Please see #22 .


Duplicate of #22.

**Closed by rushter** 2021-03-18 06:37 UTC
