### ISSUE TITLE
Segmentation fault (core dumped) when calling "attributes" of a node

### ISSUE THREAD

**Issue by aleasims** [rushter/selectolax#9] opened 2019-02-12 11:45 UTC
First of all, thanks for a really good and extremely fast HTML-parser in Python.
I came across a problem with this file:
[bad_html.txt](https://github.com/rushter/selectolax/files/2855512/bad_html.txt)
(Probably it was corrupted while dumping, but here it doesn't matter)

I am finding meta-tags in it using HTMLParser.tags() function and then I'm trying to access attributes of found nodes. And on 4-th node python collapses with segfault.
Code:
```
html = open(path, 'r').read()
parser = HTMLParser(html)
for tag in parser.tags('meta'):
    print(tag.attributes)
```
Result:
```
{'charset': 'utf-8'}
{'content': 'IE=edge', 'http-equiv': 'X-UA-Compatible'}
{'content': 'ÑÐ½Ð¸ÐºÐ°, ÑÐ¾Ð·ÐµÑÐºÐ¸ Ð¸ Ð²ÑÐºÐ»ÑÑÐ°ÑÐµÐ»Ð¸ ÑÐ½Ð°Ð¹Ð´ÐµÑ, Ð²ÑÐºÐ»ÑÑÐ°ÑÐµÐ»Ð¸ schneider electric, ÑÐ¾Ð·ÐµÑÐºÐ¸ ÑÐ½Ð°Ð¹Ð´ÐµÑ, ÑÐ¾Ð·ÐµÑÐºÐ¸ schneider, schneider electric ÑÐ¾Ð·ÐµÑÐºÐ¸ Ð¸ Ð²ÑÐºÐ»ÑÑÐ°ÑÐµÐ»Ð¸, Ð²ÑÐºÐ»ÑÑÐ°ÑÐµÐ»Ð¸ ÑÐ½Ð°Ð¹Ð´ÐµÑ, unica ÑÐ¾Ð·ÐµÑÐºÐ¸, unica schneider, Ð²ÑÐºÐ»ÑÑÐ°ÑÐµÐ»Ð¸ unica, schneider electric unica, ÑÐ°Ð¼ÐºÐ¸ unica, Ð\xa0Ð¾Ð·ÐµÑÐºÐ¸ schneider electric, ÑÐ¾Ð·ÐµÑÐºÐ¸ ÑÐ½Ð°Ð¹Ð´ÐµÑ ÑÐ»ÐµÐºÑÑÐ¸Ðº', 'name': 'keywords'}
Segmentation fault (core dumped)
```
The fact that you cannot handle SIGSEGV signals in Python properly makes it more sad.

Hope, you will be able to handle this "fatal error".

My params:
- selectolax 0.1.9
- Python 3.5.2
- Linux 4.15.0-45-generic (Ubuntu 16.04)

**UPDATE**
Maybe I've found out the weak place, because:
```
html = open(path, 'r').read()
parser = HTMLParser(html)
parser = HTMLParser(parser.html)
for tag in parser.tags('meta'):
    print(tag.attributes)
```
works! Symbol " occurs inside meta tag and this builds a problem. Maybe helpful to look at differences between origin html text, parser.html and HTMLParser(parser.html).html

**Comment by rushter** [comment] 2019-02-13 21:16
I've fixed your problem.

Don't close this ticket. I will investigate it further a later because I'm not sure if that's expected behavior from the `Modest` engine.

**Comment by aleasims** [comment] 2019-02-18 09:46
Great, it seems to work fine now! Thank you very much for quickly solving the issue.

**Closed** 2019-04-03 09:23 UTC
